Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from spycci.systems import System
water = System("../example_files/water.xyz")
print(water)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01mspycci[39;00m[38;5;21;01m.[39;00m[38;5;21;01msystems[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m System
[1;32m      2[0m water [38;5;241m=[39m System([38;5;124m"[39m[38;5;124m../example_files/water.xyz[39m[38;5;124m"[39m)
[1;32m      3[0m [38;5;28mprint[39m(water)

File [0;32m/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/spycci/__init__.py:1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01mspycci[39;00m[38;5;21;01m.[39;00m[38;5;21;01mengines[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdftbplus[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m DFTBInput
[1;32m      2[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01mspycci[39;00m[38;5;21;01m.[39;00m[38;5;21;01mengines[39;00m[38;5;21;01m.[39;00m[38;5;21;01morca[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m OrcaInput, M06, CCSD, r2SCAN
[1;32m      3[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01mspycci[39;00m[38;5;21;01m.[39;00m[38;5;21;01mengines[39;00m[38;5;21;01m.[39;00m[38;5;21;01mxtb[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m XtbInput

[0;31mModuleNotFoundError[0m: No module named 'spycci.engines'

